"""database_revision

Revision ID: 236d3942490a
Revises: 
Create Date: 2026-05-13 17:14:55.082050

"""
from alembic import op
import sqlalchemy as sa


revision = '236d3942490a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
