"""Initial migration

Revision ID: 553214d41350
Revises: bb78cf6c84b5
Create Date: 2026-05-13 16:26:08.765385

"""
from alembic import op
import sqlalchemy as sa


revision = '553214d41350'
down_revision = 'bb78cf6c84b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
