"""Initial migration

Revision ID: bb78cf6c84b5
Revises: 
Create Date: 2026-05-13 15:50:53.298849

"""
from alembic import op
import sqlalchemy as sa


revision = 'bb78cf6c84b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
